import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/app/theme';
import './globals.css';
import { UserStoreProvider } from '@/app/providers/user-store-provider';
import { RatingsStoreProvider } from '@/app/providers/ratings-store-provider';
import { WatchlistStoreProvider } from '@/app/providers/watchlist-store-provider';

export const metadata: Metadata = {
  title: 'Movie Base',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <UserStoreProvider>
              <RatingsStoreProvider>
                <WatchlistStoreProvider>
                  {children}
                </WatchlistStoreProvider>
              </RatingsStoreProvider>
            </UserStoreProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
